# Generated by Django 5.1.6 on 2025-03-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
