# Generated by Django 5.1.6 on 2025-03-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=500)),
                ('num_likes', models.IntegerField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=50)),
                ('apartment_series', models.CharField(max_length=50)),
                ('heating', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('furniture', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('floor', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('wall_material', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('num_likes', models.IntegerField(default=0)),
                ('region', models.CharField()),
                ('city', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField()),
            ],
        ),
    ]
