# Generated by Django 5.1.6 on 2025-03-01 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('num_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.listing')),
                ('replied_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listingcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=50)),
                ('apartment_series', models.CharField(max_length=50)),
                ('heating', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('furniture', models.CharField(max_length=50)),
                ('rooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('floor', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('wall_material', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='listings.listing')),
            ],
        ),
    ]
