# Generated by Django 5.1.6 on 2025-02-25 16:58

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingpicture',
            name='path',
        ),
        migrations.AddField(
            model_name='listingpicture',
            name='image',
            field=models.ImageField(default='none', upload_to=listings.models.ListingPicture.listing_image_path),
            preserve_default=False,
        ),
    ]
