# Generated by Django 5.1.6 on 2025-03-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
