# Generated by Django 5.1.6 on 2025-03-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_num_likes_remove_listingdetail_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
