# Generated by Django 5.1.6 on 2025-04-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_num_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.TextField()),
                ('option', models.TextField()),
            ],
        ),
    ]
