# Generated by Django 5.1.6 on 2025-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingdetail',
            name='city',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingdetail',
            name='region',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
