# Generated by Django 5.1.6 on 2025-03-02 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppealPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_base64', models.TextField()),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='support.appeal')),
            ],
        ),
    ]
