# Generated by Django 5.1.6 on 2025-03-02 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='last_answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
